services:
  - type: web
    name: beauty-bot
    runtime: python
    repo: https://github.com/ketistar85-crypto/beauty-bot
    plan: free
    envVars:
      - key: TOKEN
        value: f9LHodD0cOJYH8sP72m2pFJE_o24qmn2XStQ0cbFAhOO_6xjZ0bR3H-whqxJYNT8tEGc6o8YfnIQC06tYyRM
      - key: DATABASE_URL
        value: postgresql://beauty_user:oV11LlRKjI48rMup4S4HCry1118SzNvJ@dpg-d8m6sojeo5us738majs0-a/beauty_db_w3v4
